from views import *
url_patterns = [
    ('/', home),
    ('/student/login', student_login),
    ('/lecturer/login', lecturer_login),
    ('/admin/login', admin_login),
    ('/student/signup', student_signup),
    ('/lecturer/signup', lecturer_signup),
    ('/admin/signup', admin_signup),
    ('/student/forgot_password', student_forgot_password),
    ('/lecturer/forgot_password', lecturer_forgot_password),
    ('/admin/forgot_password', admin_forgot_password),
    ('/admin/', admin_home),
    ('/student/', student_home),
    ('/lecturer/', lecturer_home),
    ('/student/logout', student_logout),
    ('/lecturer/logout', lecturer_logout),
    ('/admin/logout', admin_logout),
    ('/student/exam', exam),
    ('/lecturer/monitor_exam', invigilate_exam),
    ('/lecturer/check_for_plagiarism', check_for_plagiarism),
    ('/admin/sample_analysis', sample_analysis),
    ('/admin/analysis', analysis),
    ('/admin/monitor_exam', monitor_exam),
    ('/assets/images/404(comp).png', comp),
    ('/assets/images/404(phone).png', phone),
    ('/assets/images/nav.png', nav_icon),
    ('/assets/images/favicon.png', favicon),
    ('/assets/images/Logo-final(white).png', white_logo),
    ('/assets/images/Logo-final(green).png', green_logo),
    ('/assets/images/github.png', github),
    ('/assets/images/instagram.png', instagram),
    ('/assets/images/linkedin.png', linkedin),
    ('/assets/images/twitter.png', twitter),
    ('/assets/images/among-us-7.gif', gif),
    ('/assets/images/dataframe.png', dataframe),
    ('/assets/static/login.css', logincss),
    ('/assets/static/basicpage.css', basicpagecss),
    ('/assets/static/404.css', notfoundcss),
    ('/assets/static/index.js', indexjs),
]

